### ISSUE TITLE
Make logo smaller and make sure it isn't blurry

### ISSUE THREAD

**Issue by jhauserw3241** [pastly/cdcdb-webserver#134]
In the static directory on the master branch, there are two images. The file called "logo-large.png" is the image that is almost 3000px wide. The file called "logo.png" is the image that is 300px wide. The problem with the "logo.png" file is that it make the logo blurry.

Original image (Purple):
![cdc_purple](https://cloud.githubusercontent.com/assets/8853535/20867150/61c0310c-ba03-11e6-85dc-1576689fa4fb.png)

Image after I turned it white with a transparent background:
![cdclogowhite](https://cloud.githubusercontent.com/assets/8853535/20867156/7bcedcf6-ba03-11e6-9b9f-f153c0cac3ff.png)

**Comment by pastly** [comment]
I can't convince myself I'm getting anything better than what Joy got, so I'm closing this in light of a lack of a source image (such as svg).
