### ISSUE TITLE
Don't make links when user can't view destination

### ISSUE THREAD

**Issue by pastly** [pastly/cdcdb-webserver#17]
Might be hard in some specific instances.

Example: don't link to an individual's people/show.html if they can't go there.

**Comment by jhauserw3241** [comment]
We had a group discussion and decided that a person should be able to see the information that already appears on the cards on the overlay even if they are logged in without any permissions.

Solution is here: https://github.com/pastly/cdcdb-webserver/commit/1dba91cc70a4df19ff16a61c32cadb25c3b04bbb
